
[project]
name = "hospitalmanagement"
version = "0.1.0"
description = "Hospital Management System"
readme = "README.md"
requires-python = ">=3.11,<3.14"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "pydantic"
]

[project.scripts]
hospitalmanagement = "hospitalmanagement.main:app"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

